export const ENV = {
  PORT: Number(Bun.env.PORT),
  REDIS_PASSWORD: Bun.env.REDIS_PASSWORD!,

  DATABASE_URL: Bun.env.DATABASE_URL!,
  GOOGLE_OAUTH_CLIENT_ID: Bun.env.GOOGLE_OAUTH_CLIENT_ID!,
  GOOGLE_OAUTH_CLIENT_SECRET: Bun.env.GOOGLE_OAUTH_CLIENT_SECRET!,
  GOOGLE_OAUTH_REDIRECT_URL: Bun.env.GOOGLE_OAUTH_REDIRECT_URL!,
  GITHUB_CLIENT_SECRET: Bun.env.GITHUB_CLIENT_SECRET!,
  GITHUB_CLIENT_ID: Bun.env.GITHUB_CLIENT_ID!,
  SESSION_SECRET: Bun.env.SESSION_SECRET!,
};
