export const ENV = {
  PORT: Number(process.env.PORT),
  REDIS_PASSWORD: process.env.REDIS_PASSWORD!,

  DATABASE_URL: process.env.DATABASE_URL!,

  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID!,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET!,
  GOOGLE_OAUTH_REDIRECT_URL: process.env.GOOGLE_OAUTH_REDIRECT_URL!,

  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET!,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID!,

  SESSION_SECRET: process.env.SESSION_SECRET!,
};
